# Generated by Django 2.1.dev20180309075957 on 2018-03-18 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=16)),
                ('jobDesc', models.CharField(max_length=16)),
                ('skillReq', models.CharField(max_length=16)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_login.UserProf'),
        ),
    ]
